name: DragonSkills
author: IDragonfire
version: 0.6
main: com.github.idragonfire.dragonskills.DragonSkillsPlugin
soft-depend: [Heroes]
commands:
  bind:
    aliases: ['b', 'dbind']
    description: bind a skill on a item (material)
    usage: /<command> [skill name]
    permission: dragonskills.bind
    permission-message: You don't have <permission>
  unbind:
    aliases: ['u', 'dunbind']
    description: unbind the current material
    usage: /<command>
    permission: dragonskills.unbind
    permission-message: You don't have <permission>
  skill:
    aliases: ['s', 'dskill']
    description: use a skill
    usage: /<command> [skill name] {player name}
    permission: dragonskills.skill
    permission-message: You don't have <permission>
  skills:
    aliases: ['slist', 'dskills]
    description: show all skills
    usage: /<command>
    permission: dragonskills.skill_list
  skilldesc:
    alias: ['shelp', 'dshelp']
    description: show skill description
    usage: /<command> [skill name]
    permission-message: You don't have <permission>
  cd:
    alias: ['cooldown', 'dcd']
    description: show skill cooldwn
    usage: /<command> [skill name] {player name}
    permission-message: You don't have <permission>    
    
permissions:
  dragonskills.skill.*:
      description: perm to execute all skills