name: DragonSkills
author: IDragonfire
version: 0.7
main: com.github.idragonfire.dragonskills.DragonSkillsPlugin
soft-depend: [Heroes]
commands:
  bind:
    aliases: ['b', 'dbind']
    description: bind a skill on a item (material)
    usage: /<command> [skill name]
    permission: dragonskills.bind
    permission-message: You don't have <permission>
  unbind:
    aliases: ['u', 'dunbind']
    description: unbind the current material
    usage: /<command>
    permission: dragonskills.unbind
    permission-message: You don't have <permission>
  skill:
    aliases: ['s', 'dskill']
    description: use a skill
    usage: /<command> [skill name] {player name}
    permission: dragonskills.skill
    permission-message: You don't have <permission>
  skills:
    aliases: ['slist', 'dskills']
    description: show all skills
    usage: /<command>
    permission: dragonskills.skills
    permission-message: You don't have <permission>
  skilldesc:
    aliases: ['shelp', 'dshelp']
    description: show skill description
    usage: /<command> [skill name]
    permission: dragonskills.skilldesc
    permission-message: You don't have <permission>
  cd:
    aliases: ['cooldown', 'dcd']
    description: show skill cooldwn
    usage: /<command> [skill name] {player name}
    permission: dragonskills.cd
    permission-message: You don't have <permission> 
  addchunk:
    aliases: ['daddchunk']
    description: add a chunk to skill free region
    usge: /<command>
    permission: dragonskills.addchunk
    permission-message: You don't have <permission> 
  removechunk:
    aliases: ['dremovechunk']
    description: remove a chunk to skill free region
    usge: /<command>
    permission: dragonskills.removechunk
    permission-message: You don't have <permission> 
    
permissions:
  dragonskills.skill.*:
      description: perm to execute all skills