name: DragonSkills
author: IDragonfire
version: 0.1
main: com.github.idragonfire.dragonskills.DragonSkillsPlugin
commands:
  bind:
    aliases: ['b']
    description: bind a skill on a item (material
    usage: /<command> [skill name]
    permission: dragonskills.bind
    permission-message: You don't have <permission>
  skill:
    aliases: ['s']
    description: use a skill
    usage: /<command> [skill name]
    permission: dragonskills.skill
    permission-message: You don't have <permission>
  skill_list:
    aliases: ['skills', 'skillist']
    description: show all skills
    usage: /<command>
    permission: dragonskills.skill_list
    permission-message: You don't have <permission>