name: DragonSkills
author: IDragonfire
version: 0.1
main: com.github.idragonfire.dragonskills.DragonSkillsPlugin
commands:
  bind:
    aliases: ['b']
    description: bind a skill on a item (material
    usage: /<command> [skill name]
    permission: dragonskills.bind
    permission-message: You don't have <permission>
  unbind:
    aliases: ['u']
    description: unbind the current material
    usage: /<command>
    permission: dragonskills.unbind
    permission-message: You don't have <permission>
  skill:
    aliases: ['s']
    description: use a skill
    usage: /<command> [skill name]
    permission: dragonskills.skill
    permission-message: You don't have <permission>
  skills:
    aliases: ['skill_list']
    description: show all skills
    usage: /<command>
    permission: dragonskills.skill_list
  skilldesc:
    alias: ['skillhelp']
    description: show skill description
    usage: /<command> [skill name]
    permission-message: You don't have <permission>